-- MySQL Script generated by MySQL Workbench
-- Thu Nov 17 17:23:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema GroupProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GroupProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GroupProject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `GroupProject` ;

-- -----------------------------------------------------
-- Table `GroupProject`.`Plant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GroupProject`.`Plant` (
  `plant_ID` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `manager_name` VARCHAR(255) NULL DEFAULT NULL,
  `manager_contact_number` VARCHAR(15) NULL DEFAULT NULL,
  `number_units` INT DEFAULT 0,
  PRIMARY KEY (`plant_ID`),
  UNIQUE INDEX `plantID_UNIQUE` (`plant_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GroupProject`.`Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GroupProject`.`Unit` (
  `unit_ID` INT NOT NULL,
  `plant_ID` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `manager_name` VARCHAR(255) NULL DEFAULT NULL,
  `manager_contact_number` VARCHAR(255) NULL DEFAULT NULL,
  `number_boilers` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`unit_ID`),
  INDEX `plant_ID_FK_idx` (`plant_ID` ASC) VISIBLE,
  CONSTRAINT `plant_ID_FK`
    FOREIGN KEY (`plant_ID`)
    REFERENCES `GroupProject`.`Plant` (`plant_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GroupProject`.`Boiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GroupProject`.`Boiler` (
  `boiler_ID` INT NOT NULL,
  `unit_ID` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `purchase_date` DATETIME NOT NULL,
  `purchase_price` FLOAT NOT NULL,
  `functionality_description` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NOT NULL,
  `boiler_status` VARCHAR(255) NULL DEFAULT NULL,
  `production_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`boiler_ID`),
  INDEX `unit_ID_FK_idx` (`unit_ID` ASC) VISIBLE,
  INDEX `coalType_idx` (`boiler_ID` ASC) VISIBLE,
  CONSTRAINT `unit_ID_FK`
    FOREIGN KEY (`unit_ID`)
    REFERENCES `GroupProject`.`Unit` (`unit_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GroupProject`.`Coal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GroupProject`.`Coal` (
  `coal_type` VARCHAR(45) NOT NULL,
  `sulfur_content` FLOAT NULL DEFAULT NULL,
  `unit_cost` FLOAT NULL DEFAULT NULL,
  `price_per_unit_allowance` FLOAT NULL DEFAULT NULL,
  `scrubber_rate` FLOAT NULL DEFAULT NULL,
  `heat_rate` FLOAT NULL DEFAULT NULL,
  `coal_burn_rate` FLOAT NULL DEFAULT NULL,
  `emittion_rate` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`coal_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `GroupProject`.`BoilerActivity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GroupProject`.`BoilerActivity` (
  `boiler_activity_ID` INT NOT NULL,
  `boiler_ID` INT NOT NULL,
  `coal_type` VARCHAR(255) NOT NULL,
  `amount_coal_to_burn` FLOAT NULL DEFAULT NULL,
  `sulfur_emitted` FLOAT NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  `energy_generated` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`boiler_activity_ID`),
  INDEX `boiler_ID_idx` (`boiler_ID` ASC) VISIBLE,
  INDEX `coal_type_FK_idx` (`coal_type` ASC) VISIBLE,
  CONSTRAINT `boiler_ID_FK`
    FOREIGN KEY (`boiler_ID`)
    REFERENCES `GroupProject`.`Boiler` (`boiler_ID`),
  CONSTRAINT `coal_type_FK`
    FOREIGN KEY (`coal_type`)
    REFERENCES `GroupProject`.`Coal` (`coal_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
